- name: check if helm is installed /usr/local/bin/helm
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_check

- name: Download get-helm-3
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: ~/get-helm-3.sh
    mode: "700"
  when: not helm_check.stat.exists

- name: install helm if not exist
  ansible.builtin.command: >-
        ~/get-helm-3.sh
  when: not helm_check.stat.exists
  changed_when: true

- name: Install Helm diff plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present