---

timezone: Your/Timezone

k3s_version: v1.30.2+k3s2
k3s_token: some-SUPER-DEDEUPER-secret-password
server_args: >-
  --tls-san {{ master_vip }}
  --disable servicelb
  --disable traefik
agent_args: 

kube_vip_version: v0.8.2
master_vip: 192.168.30.222
vip_interface: eth0


