ingress:
  enabled: true
  className: nginx-internal
  hosts:
    - host: homeassist.lhmn.cc
      paths:
        - path: /
          pathType: ImplementationSpecific
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: nfs-generic
hostNetwork: true
configuration:
  enabled: true
  forceInit: true
  trusted_proxies:
    - 10.42.0.0/16
  templateConfig: |-
    # Loads default set of integrations. Do not remove.
    default_config:

    {{- if .Values.ingress.enabled }}
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        {{- range .Values.configuration.trusted_proxies }}
        - {{ . }}
        {{- end }}
    {{- end}}