---
ingress:
  enabled: true
  ingressClassName: nginx-internal
  hosts:
    - pihole.lhmn.cc
DNS1: 192.168.0.1
DNS2: 192.168.0.1
persistentVolumeClaim:
  enabled: true
  storageClass: nfs-pihole
serviceWeb:
  loadBalancerIP: 192.168.0.30
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.0.30
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
