---
persistentVolumeClaim:
  enabled: true
  storageClass: nfs-client
serviceWeb:
  loadBalancerIP: 192.168.0.31
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDNS:
  loadBalancerIP: 192.168.0.31
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
