---
- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
      become: true

- name: Setup k3s master
  hosts: master
  become: true
  vars_files:
    - secrets.yml
  roles:
    - role: master

- name: Setup k3s agents
  hosts: agent
  become: true
  vars_files:
    - secrets.yml
  roles:
    - role: agent

- name: Storing kubeconfig in the playbook directory
  hosts: master
  tasks:
    - name: Copying kubeconfig from master
      ansible.builtin.fetch:
        src: "/etc/rancher/k3s/k3s.yaml"
        dest: ./kubeconfig
        flat: true
      when: inventory_hostname == groups.master[0]
