---

timezone: Europe/Berlin
k3s_version: v1.31.1+k3s1
kube_vip_version: v0.8.4
master_vip: 192.168.0.20
vip_interface: eth0
server_args: >-
  --tls-san {{ master_vip }}
  --disable servicelb
  --disable traefik
agent_args: ""





