---
- name: Create manifests directory on first master
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups.master[0]

- name: Deploy vip manifest
  ansible.builtin.include_tasks: kube-vip.yml

# Only run bootstrap block for first init
- name: Bootstrap cluster
  ansible.builtin.include_tasks: bootstrap_cluster.yml
  when: bootstrap_cluster | default(False)

- name: Copy K3s service file
  register: k3s_service
  ansible.builtin.template:
    src: k3s.service.j2
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: "0644"

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: started
    enabled: true

- name: Deploy metallb manifest
  ansible.builtin.include_tasks: metallb.yml

- name: Change k3s.yaml permissions to 644
  file:
    path: /etc/rancher/k3s/k3s.yaml
    owner: "{{ ansible_user }}"
    mode: "644"

- name: Configure kubectl cluster to {{ master_vip }}
  ansible.builtin.command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ master_vip }}:6443
      --kubeconfig /etc/rancher/k3s/k3s.yaml
  changed_when: true
  when: bootstrap_cluster | default(False)

- name: Create kubectl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
