---
- name: Create manifests directory on first master
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups.master[0]

- name: "Download to first master: manifest for metallb-native"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml
    dest: /var/lib/rancher/k3s/server/manifests/metallb-crds.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups.master[0]
