---
- name: Copy nfs pv manifest to first master
  ansible.builtin.template:
    src: nfs-pv.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/nfs-pv.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups.master[0]
