---
- name: Check if nfs namespace exists 
  ansible.builtin.shell:
    kubectl get namespaces -o=jsonpath="{range .items[*]}{.metadata.name}{'\n'}{end}" | grep nfs-system
  changed_when: false
  failed_when: false 
  register: namespace
  when: inventory_hostname == groups.master[0]


- name: Create namespace for nfs provisioner
  ansible.builtin.command:
    k3s kubectl create namespace nfs-system
  when: inventory_hostname == groups.master[0] and namespace.rc != 0

- name: Copy nfs rbac manifest to first master
  ansible.builtin.template:
    src: nfs-rbac.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/nfs-rbac.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups.master[0]

- name: Copy nfs rbac manifest to first master
  ansible.builtin.template:
    src: nfx-deployment.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/nfx-deployment.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups.master[0]

- name: Copy nfs storage class manifest to first master
  ansible.builtin.template:
    src: nfs-class.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/nfs-class.yaml
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname == groups.master[0]
