---
- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
      become: true

- name: Setup k3s master
  hosts: master
  become: true
  vars_files:
    - secrets.yml
  roles:
    - role: master
    - role: master-post

- name: Setup k3s agents
  hosts: agent
  become: true
  vars_files:
    - secrets.yml
  roles:
    - role: agent
