repositories:
  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: emby 
    url: https://pmoscode-helm.github.io/emby
    
  
---
releases:
  - name: nfs-generic
    namespace: nfs-system
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    values: 
      - ./values/nfs-generic.values.yml
  
  - name: nfs-pihole
    namespace: pihole-system
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    values: 
      - ./values/nfs-pihole.values.yml

  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.1
    values:
      - ./values/pihole.values.yml
  
  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.11.3
    values:
      - ./values/nginx.values.yml
  
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.5.1
    values:
      - ./values/externaldns.values.yml
  
  - name: emby
    namespace: emby-system
    chart: emby/emby
    version: 1.3.0
    values:
      - ./values/emby.values.yml

