repositories:
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes
  
---
releases:
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.1
    values:
      - ./values/pihole.values.yml