repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
---
releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.2
  
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.14.8
    values:
      - ./values/metallb.values.yml